### ISSUE TITLE
右击事件bug

### ISSUE THREAD

**Issue by jayce1212** [moyuanz/DevilYuan#12]
## 报错信息
Traceback (most recent call last):
  File "/Users/Documents/DevilYuan/DyCommon/Ui/DyStatsTableWidget.py", line 65, in _showHeaderContextMenu
    self.customizeHeaderContextMenu(self._rightClickHeaderItem)
  File "/Users/Documents/DevilYuan/Stock/Common/Ui/Basic/DyStockTableWidget.py", line 1310, in customizeHeaderContextMenu
    self._upDownRatioAction.setEnabled('涨幅' in headerItem.text())
AttributeError: 'NoneType' object has no attribute 'text'

## 导致结果
程序崩溃，进程直接退出。

## 界面
![image](https://user-images.githubusercontent.com/44791674/53875912-9b5a9400-4040-11e9-84a6-886376ba5ead.png)

**Comment by moyuanz** [comment]
bug fix
